apiVersion: v1
kind: Service
metadata:
    name: caddy
    labels:
        run: caddy
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
    selector:
        run: caddy
