version: '3.0'

services:
    caddy:
        image: docker.io/procsiab/caddy:latest
        container_name: caddy
        ports:
            - "0.0.0.0:80:80/tcp"
            - "0.0.0.0:443:443/tcp"
        volumes:
            - ./config/:/config:Z
            - ./data/:/data:Z
            - ./Caddyfile/:/etc/caddy/Caddyfile:Z
        env_file:
            - ./secrets.env
        environment:
            - CADDYFILE_PATH: "/etc/caddy/Caddyfile"
        cap_add:
            - NET_BIND_SERVICE
