#!/bin/bash

# Obtain the Dockerfile name with extension
BUILD_ARCH=$(basename "${DOCKERFILE_PATH}")

# If no extension is found, assume x86_64 target, or else extract the extension
if [[ "${BUILD_ARCH}" == "Dockerfile" ]]
then
    echo 'qemu-user-static: Download not required for current arch'
    exit 0
else
    BUILD_ARCH=$(echo "$BUILD_ARCH" | cut -d '.' -f 2)
fi

# Fix arm 32 bit v7 arch target to match qemu file name of arm (strips last 2 characters)
QEMU_USER_STATIC_ARCH=$([ "${BUILD_ARCH}" == "armv7" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}")
# Build the download URL ased on the target architecture
QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
# Format the latest QEMU's version tag from GitHub's APIs
QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
    | grep 'name.*v[0-9]' \
    | head -n 1 \
    | cut -d '"' -f 4)

# Download and extract the QEMU static binary in the container build root
curl -SL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" | tar xzv
